/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author thiagoalmeida
 */
public class OrcamentoAtualizar extends CustomJPanel {

    /**
     * Creates new form OrcamentoAtualizar
     */
    private DefaultListModel modelGastos, modelReceitas;
    public OrcamentoAtualizar() {
        initComponents();
        
        modelGastos = new DefaultListModel();
        modelReceitas = new DefaultListModel();
        
        jListGastos.setModel(modelGastos);
        jListReceitas.setModel(modelReceitas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelReceitas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListReceitas = new javax.swing.JList<>();
        jLabelReceitas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListGastos = new javax.swing.JList<>();
        jLabelGastos = new javax.swing.JLabel();
        jButtonRemover = new javax.swing.JButton();
        jPanelGastos = new javax.swing.JPanel();
        jLabelCadastroDe = new javax.swing.JLabel();
        jComboBoxReceitaGasto = new javax.swing.JComboBox<>();
        jLabelDescrição = new javax.swing.JLabel();
        jTextFieldDescrição = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldDateDay = new javax.swing.JTextField();
        jLabelData = new javax.swing.JLabel();
        jTextFieldDateMonth = new javax.swing.JTextField();
        jTextFieldDateYear = new javax.swing.JTextField();
        jLabelFSlash2 = new javax.swing.JLabel();
        jLabelFSlash1 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jLabelMesAtualizado = new javax.swing.JLabel();

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSplitPane1.setBorder(null);
        jSplitPane1.setDividerLocation(396);

        jListReceitas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListReceitas);

        jLabelReceitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelReceitas.setText("Receitas");

        jListGastos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListGastos);

        jLabelGastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelGastos.setText("Gastos");

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReceitasLayout = new javax.swing.GroupLayout(jPanelReceitas);
        jPanelReceitas.setLayout(jPanelReceitasLayout);
        jPanelReceitasLayout.setHorizontalGroup(
            jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReceitasLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelReceitas)
                    .addComponent(jLabelGastos)
                    .addGroup(jPanelReceitasLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonRemover)
                            .addGroup(jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanelReceitasLayout.setVerticalGroup(
            jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceitasLayout.createSequentialGroup()
                .addComponent(jLabelReceitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemover)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanelReceitas);

        jLabelCadastroDe.setText("Cadastro de");

        jComboBoxReceitaGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Receita", "Gasto" }));
        jComboBoxReceitaGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReceitaGastoActionPerformed(evt);
            }
        });

        jLabelDescrição.setText("Descrição");

        jTextFieldDescrição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescriçãoActionPerformed(evt);
            }
        });

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jLabelValor.setText("Valor");

        jTextFieldDateDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateDayActionPerformed(evt);
            }
        });

        jLabelData.setText("Data");

        jTextFieldDateMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateMonthActionPerformed(evt);
            }
        });

        jTextFieldDateYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateYearActionPerformed(evt);
            }
        });

        jLabelFSlash2.setText("/");

        jLabelFSlash1.setText("/");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGastosLayout = new javax.swing.GroupLayout(jPanelGastos);
        jPanelGastos.setLayout(jPanelGastosLayout);
        jPanelGastosLayout.setHorizontalGroup(
            jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSalvar)
                    .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelGastosLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabelDescrição)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelGastosLayout.createSequentialGroup()
                                .addComponent(jLabelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelGastosLayout.createSequentialGroup()
                                .addComponent(jLabelCadastroDe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxReceitaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188))
                            .addGroup(jPanelGastosLayout.createSequentialGroup()
                                .addComponent(jLabelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabelFSlash1)
                                .addGap(3, 3, 3)
                                .addComponent(jTextFieldDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabelFSlash2)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanelGastosLayout.setVerticalGroup(
            jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroDe)
                    .addComponent(jComboBoxReceitaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescrição)
                    .addComponent(jTextFieldDescrição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData)
                    .addComponent(jTextFieldDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFSlash1)
                    .addComponent(jLabelFSlash2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanelGastos);

        jLabelMesAtualizado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMesAtualizado.setText("Orçamento Abril 2002");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMesAtualizado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMesAtualizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jComboBoxReceitaGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReceitaGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxReceitaGastoActionPerformed

    private void jTextFieldDescriçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescriçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescriçãoActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jTextFieldDateDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateDayActionPerformed

    private void jTextFieldDateMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateMonthActionPerformed

    private void jTextFieldDateYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateYearActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxReceitaGasto;
    private javax.swing.JLabel jLabelCadastroDe;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDescrição;
    private javax.swing.JLabel jLabelFSlash1;
    private javax.swing.JLabel jLabelFSlash2;
    private javax.swing.JLabel jLabelGastos;
    private javax.swing.JLabel jLabelMesAtualizado;
    private javax.swing.JLabel jLabelReceitas;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JList<String> jListGastos;
    private javax.swing.JList<String> jListReceitas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGastos;
    private javax.swing.JPanel jPanelReceitas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldDateDay;
    private javax.swing.JTextField jTextFieldDateMonth;
    private javax.swing.JTextField jTextFieldDateYear;
    private javax.swing.JTextField jTextFieldDescrição;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

    public void addListSelectionListener(ListSelectionListener listener){
        this.jListGastos.addListSelectionListener(listener);
        this.jListReceitas.addListSelectionListener(listener);
    }
    
    public void addActionListener(ActionListener listener){
        this.jButtonRemover.addActionListener(listener);
        this.jButtonVoltar.addActionListener(listener);
        this.jButtonSalvar.addActionListener(listener);
    }
    
    public int getSelectedComboBox(){
        return this.jComboBoxReceitaGasto.getSelectedIndex();
    }

    public JButton getjButtonRemover() {
        return this.jButtonRemover;
    }

    public JButton getjButtonVoltar() {
        return this.jButtonVoltar;
    }
    
    public JButton getjButtonSalvar(){
        return this.jButtonSalvar;
    }
    
    public String getTextjTextFieldDateDay(){
        return this.jTextFieldDateDay.getText();
    }
    
    public String getTextjTextFieldDateMonth(){
        return this.jTextFieldDateMonth.getText();
    }
    
    public String getTextjTextFieldDateYear(){
        return this.jTextFieldDateYear.getText();
    }
    
    public String getTextjTextFieldValor(){
        return this.jTextFieldValor.getText();
    }
    
    public String getTextjTextFieldDescricao(){
        return this.jTextFieldDescrição.getText();
    }

    public JComboBox<String> getjComboBoxReceitaGasto() {
        return jComboBoxReceitaGasto;
    }

    public JLabel getjLabelCadastroDe() {
        return jLabelCadastroDe;
    }

    public JLabel getjLabelData() {
        return jLabelData;
    }

    public JLabel getjLabelDescrição() {
        return jLabelDescrição;
    }

    public JLabel getjLabelFSlash1() {
        return jLabelFSlash1;
    }

    public JLabel getjLabelFSlash2() {
        return jLabelFSlash2;
    }

    public JLabel getjLabelGastos() {
        return jLabelGastos;
    }

    public JLabel getjLabelMesAtualizado() {
        return jLabelMesAtualizado;
    }

    public JLabel getjLabelReceitas() {
        return jLabelReceitas;
    }

    public JLabel getjLabelValor() {
        return jLabelValor;
    }

    public JList<String> getjListGastos() {
        return jListGastos;
    }

    public JList<String> getjListReceitas() {
        return jListReceitas;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanelGastos() {
        return jPanelGastos;
    }

    public JPanel getjPanelReceitas() {
        return jPanelReceitas;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JSplitPane getjSplitPane1() {
        return jSplitPane1;
    }

    public JTextField getjTextFieldDateDay() {
        return jTextFieldDateDay;
    }

    public JTextField getjTextFieldDateMonth() {
        return jTextFieldDateMonth;
    }

    public JTextField getjTextFieldDateYear() {
        return jTextFieldDateYear;
    }

    public JTextField getjTextFieldDescrição() {
        return jTextFieldDescrição;
    }

    public JTextField getjTextFieldValor() {
        return jTextFieldValor;
    }
    
    public void addGasto(int id, float valor){
        modelGastos.addElement(id + " " + valor);
    }
    
    public void addReceita(int id, float valor){
        modelReceitas.addElement(id + " " + valor);
    }
    
    public void criarMensagemErro(String titulo, String mensagem){

        //https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html
        JOptionPane.showMessageDialog(
                this,
                mensagem,
                titulo,
                JOptionPane.ERROR_MESSAGE
            );
    }
}
